version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3.6 scrapDataMondial.py &&
             python3.6 cleanData.py &&
             python3.6 buildDemographie.py &&
             python3.6 worldApiRest/manage.py makemigrations &&
             python3.6 worldApiRest/manage.py migrate &&
             python3.6 worldApiRest/manage.py fill_data_base &&
             python3.6 worldApiRest/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
